version: '3.0'

services:
  database:
    container_name: webprovise-database
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - webprovise-db:/var/lib/postgresql
      - webprovise-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: webprovise-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secret123@
      PGDATA: /var/lib/postgresql/data/

  api:
    container_name: webprovise-api
    build:
      context: ./../
      dockerfile: docker-development/Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./../:/home/node/api
      - webprovise-node_modules:/home/node/api/node_modules
    ports:
      - '3001:3001'
    links:
      - database
    command: yarn run start:dev --watch

  portainer:
    container_name: webprovise-portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: on-failure
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - webprovise-portainer_data:/data

volumes:
  webprovise-db:
  webprovise-pgdata:
  webprovise-node_modules:
  webprovise-portainer_data:
